### ISSUE TITLE
Add a requirement of PHP 7.0+ to the composer.json

### ISSUE THREAD

**Issue by punkstar** [meanbee/magento2-webappmanifest#2]
We're using [scalar type declarations](https://secure.php.net/manual/en/migration70.new-features.php#migration70.new-features.scalar-type-declarations) in our code, meaning we need at least 7.0 installed.

First raised in #1.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
